apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kyverno-acr-creds
  namespace: kyverno
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-backend
    kind: ClusterSecretStore
  target:
    name: kyverno-acr-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "yolaprod.azurecr.io": {
                "username": "yolaprod",
                "password": "{{ .password }}"
              }
            }
          }
  data:
    - secretKey: password
      remoteRef:
        key: kyverno-acr-password
