apiVersion: v1
kind: Service
metadata:
  name: yola-backend
  namespace: yola
  labels:
    app: yola-backend
spec:
  ports:
    - port: 8706
      targetPort: 8706
      name: http
  selector:
    app: yola-backend
  type: ClusterIP
