apiVersion: v1
kind: ConfigMap
metadata:
  name: yola-backend-config
  namespace: yola
data:
  PORT: "8706"
  # проверить реальное имя через kubectl get svc -n yola после первого деплоя, Bitnami может менять схему именования между версиями чарта
  REDIS_HOST: "yola-redis-master"
  REDIS_PORT: "6379"
