# yaml-language-server: $schema=https://www.schemastore.org/any.json
#
# Кластерный ресурс ClusterSecretStore, связывающий ESO с Azure Key Vault через
# AKS Workload Identity. Service Principal secret больше не используется.
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-backend
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://yola-kv-prod.vault.azure.net"
      tenantId: "de55767a-1422-43c7-9583-f1b281fd2ffd"
      clientId: "d614f3d7-c240-4c2c-8301-664ad66865b3"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
