# yaml-language-server: $schema=https://www.schemastore.org/any.json
#
# Кластерный ресурс ClusterSecretStore, связывающий ESO с Azure Key Vault через
# AKS Workload Identity. Service Principal secret больше не используется.
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-backend
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://yola-kv-prod.vault.azure.net"
      tenantId: "84f58ce9-43c8-4932-b908-591a8a3007d3"
      clientId: "eecc05df-439a-49b6-aea0-406f73a7a1b2"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
