# yaml-language-server: $schema=https://www.schemastore.org/any.json
#
# Argo CD Application для установки External Secrets Operator (ESO) через Helm.
# ESO синхронизирует секреты из внешних систем (например, Azure Key Vault) в Kubernetes.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    # sync-wave: "0" — устанавливается самым первым, так как его CRD нужны для ClusterSecretStore
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.18
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
        podLabels:
          azure.workload.identity/use: "true"
        serviceAccount:
          annotations:
            azure.workload.identity/client-id: "eecc05df-439a-49b6-aea0-406f73a7a1b2"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
