apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-config
  namespace: argocd
  annotations:
    # sync-wave: "2" — применяется после istiod и ingressgateway
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/musaxasmammedov7/final-project-yola.git
    targetRevision: main
    path: gitops/istio
    directory:
      # Exclude the kiali-app.yaml from this Application,
      # since Kiali has its own dedicated Application manifest
      exclude: "kiali-app.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
