apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  annotations:
    # sync-wave: "1" — kiali устанавливается во второй волне
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 1.89.0
    helm:
      values: |
        auth:
          strategy: anonymous
        external_services:
          prometheus:
            url: "http://prometheus-grafana-kube-pr-prometheus.monitoring.svc.cluster.local:9090"
          grafana:
            url: "http://prometheus-grafana.monitoring.svc.cluster.local:80"
          tracing:
            url: "http://jaeger-query.monitoring.svc.cluster.local:16686"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
