apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yola-secrets
  namespace: argocd
  annotations:
    # sync-wave: "2" — ExternalSecret ресурсы создают Kubernetes Secrets до MongoDB/Redis/app
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/musaxasmammedov7/final-project-yola.git
    targetRevision: main
    path: gitops/yola-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: yola
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
