apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yola-redis
  namespace: argocd
  annotations:
    # sync-wave: "3" — redis разворачивается после синхронизации ExternalSecret
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 19.0.0
      helm:
        valueFiles:
          - $values/gitops/yola/redis-values.yaml
    - repoURL: https://github.com/musaxasmammedov7/final-project-yola.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: yola
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
