apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-config
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-backend
    kind: ClusterSecretStore
  target:
    name: alertmanager-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
            smtp_smarthost: "smtp.gmail.com:587"
            smtp_from: "musaxasmammedov77@gmail.com"
            smtp_auth_username: "musaxasmammedov77@gmail.com"
            smtp_auth_password: "{{ .smtp_password }}"
            smtp_require_tls: true
          route:
            group_by: ["alertname", "namespace"]
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 4h
            receiver: "multi-channel"
            routes:
              - match:
                  severity: critical
                receiver: "multi-channel"
                repeat_interval: 1h
          receivers:
            - name: "multi-channel"
              email_configs:
                - to: "musaxasmammedov77@gmail.com"
                  send_resolved: true
              telegram_configs:
                - bot_token: "{{ .telegram_token }}"
                  chat_id: 7538711142
                  parse_mode: "HTML"
                  send_resolved: true
  data:
    - secretKey: smtp_password
      remoteRef:
        key: alertmanager-smtp-password
    - secretKey: telegram_token
      remoteRef:
        key: alertmanager-telegram-token
