# Helm values for Jaeger with Elasticsearch backend
provisionDataStore:
  cassandra: false
  elasticsearch: true

allInOne:
  enabled: false

agent:
  enabled: false

storage:
  type: elasticsearch
  elasticsearch:
    host: jaeger-elasticsearch
    port: 9200

# Disable Badger persistence since we are using Elasticsearch now
persistence:
  enabled: false

# Configuration for the provisioned Bitnami Elasticsearch subchart
elasticsearch:
  image:
    registry: docker.io
    repository: bitnamilegacy/elasticsearch
    tag: 8.13.2-debian-12-r0
  sysctlImage:
    enabled: false
    repository: bitnamilegacy/os-shell
    tag: 12-debian-12-r18
  sysctl:
    enabled: false
    image:
      registry: docker.io
      repository: bitnamilegacy/os-shell
      tag: 12-debian-12-r18
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
      tag: 12-debian-12-r18
  security:
    enabled: false
  master:
    masterOnly: false
    replicaCount: 1
    persistence:
      size: 5Gi
      storageClass: "yola-azure-disk"
    resources:
      requests:
        cpu: "50m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    heapSize: "512m"
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    enabled: false

collector:
  service:
    otlp:
      grpc:
        enabled: true
        name: otlp-grpc
        port: 4317
      http:
        enabled: true
        name: otlp-http
        port: 4318
    zipkin:
      port: 9411

query:
  service:
    type: ClusterIP
    port: 16686
    annotations: {}
