apiVersion: v1
kind: Service
metadata:
  name: yola-mongo
  namespace: yola
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: ExternalName
  externalName: yola-mongo-svc.yola.svc.cluster.local
