apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: yola-frontend-secrets
  namespace: yola
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-backend
    kind: ClusterSecretStore
  target:
    name: yola-frontend-secrets
    creationPolicy: Owner
  data:
    - secretKey: GROQ_API_KEY
      remoteRef:
        key: groq-api-key
