# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-root-password
  namespace: yola
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-backend
    kind: ClusterSecretStore
  target:
    name: mongodb-root-password-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: mongodb-root-password

